name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
    - name: Upload artifact to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist
        asset_name: dist
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
