name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    
    - name: download artifact
      uses: actions/download-artifact@v3
        
    - name: upload artifact to release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        files: /home/runner/work/quicker-zen/quicker-zen/artifact
        draft: false
