name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    
    - name: download artifact
      uses: actions/download-artifact@v3
        
    - name: upload artifact to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/quicker-zen/quicker-zen/artifact
        asset_name: dist
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
